-- 0001_raw_trend_images.sql
-- Spec section 9.1. Raw collected image records (Layer 1 output).
-- Note: UUIDs are generated by the application (crypto.randomUUID) so this
-- SQL is identical on real PostgreSQL and the embedded PGlite demo database.

CREATE TABLE IF NOT EXISTS raw_trend_images (
  id             uuid PRIMARY KEY,
  source         varchar(50)  NOT NULL,               -- pinterest / vogue / filmfare / fdci-lakme / nykaa-myntra / instagram
  source_url     text         NOT NULL UNIQUE,        -- original page/pin URL (dedup key across runs)
  image_url      text         NOT NULL,               -- direct CDN URL of the image
  image_s3_key   text,                                -- our S3/local backup key (NULL when backup failed)
  raw_metadata   jsonb        NOT NULL DEFAULT '{}'::jsonb,  -- full raw API/scraper response
  collected_at   timestamptz  NOT NULL DEFAULT now(),
  status         varchar(20)  NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending', 'analysis_failed', 'analyzed', 'scored', 'discarded'))
);

-- Polling queue for the analysis workflow (batches of 20 'pending' rows).
CREATE INDEX IF NOT EXISTS idx_raw_trend_images_status_collected
  ON raw_trend_images (status, collected_at);

-- Feed filtering is date-driven (spec: date_from / date_to).
CREATE INDEX IF NOT EXISTS idx_raw_trend_images_collected_at
  ON raw_trend_images (collected_at);

CREATE INDEX IF NOT EXISTS idx_raw_trend_images_source
  ON raw_trend_images (source);